package cook.ref

import cook.error.ErrorTracking._

import scala.annotation.tailrec
import scala.tools.nsc.io.{ Path => SPath, Directory }


/**
 * Directory reference.
 *
 * segments is start from cook root.
 *
 * @author iamtimgreen@gmail.com (Tim Green)
 */
class DirRef(val segments: List[String]) {

  def toDir: Directory = segments.foldLeft(Path().rootDir)(_ / _)
  override def refName: String = segments.mkString("", "/", "/")

  def / (lastPart: String): PathRef = {

  }
}

object DirRefFactory extends RefFactory[DirRef] {

  override def apply(refName: String): Option[DirRef] = {
    // TODO(timgreen):
  }
}

abstract class PathRef(val dir: DirRef, lastPart: String)

class FileRef(dir: DirRef, val filename: String) extends PathRef(dir, filename) {

  def toPath: SPath = dir.toDir / filename
  override def refName: String =  dir.refName + "/" + filename
}

object FileRefFactory extends RefFactory[FileRef] {

  override def apply(refName: String): Option[FileRef] = {

  }
}

class TargetRef(dir: DirRef, val targetName: String) extends PathRef(dir, targetName) {

  override def refName: String =  dir.refName + ":" + targetName
  def cookFileRef: FileRef = new FileRef(dir, "COOK")
}

object TargetRefFactory extends RefFactory[TargetRef] {

  override def apply(refName: String): Option[TargetRef] = {

  }
}

trait PluginRef extends Ref

trait PluginRefFactory[P >: PluginRef] extends RefFactory[P] {

  val pluginName: String

  override def apply(refName: String): Option[P] = {
    val prefix = "//" + pluginName + "/"
    if (refName.startsWith(prefix)) {
      parseRefName(refName.dropLeft(prefix.size)
    } else {
      None
    }
  }

  def parseRefName(refName: String): Option[P]
}

// TODO(timgreen): Plugin Target ref
// Start with //<plugin_name>/
// e.g. //mvn/com.github.scopt%%scopt%2.1.0"
// can be generated by some helper function like:
// mvn / "com.github.scopt" %% "scopt" % "2.1.0"
